version: '3.8'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=/server/server.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
      - OPENAI_API_KEY=sk-KEY
    volumes:
      - "./data:/data"
